package com.axibase.tsd.api.model.series.query.transformation.group;

public enum GroupType {
    COUNT,
    MIN,
    MAX,
    AVG,
    SUM,
    PERCENTILE_999,
    PERCENTILE_995,
    PERCENTILE_99,
    PERCENTILE_95,
    PERCENTILE_90,
    PERCENTILE_75,
    PERCENTILE_50,
    PERCENTILE_25,
    PERCENTILE_10,
    PERCENTILE_5,
    PERCENTILE_1,
    PERCENTILE_05,
    PERCENTILE_01,
    MEDIAN,
    MEDIAN_ABS_DEV,
    STANDARD_DEVIATION,
    FIRST,
    LAST,
    MIN_VALUE_TIME,
    MAX_VALUE_TIME,
    DETAIL,
    OHLCV,
    VWAP,
    OPEN,
    CLOSE
}
